name: tripper
description: 'Your trip companion, whever you go.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.2.2
  hooks_riverpod: ^2.4.9
  rxdart: ^0.27.7
  google_maps_flutter: ^2.2.8
  geolocator: ^10.1.0
  flutter_gemini: ^2.0.1
  flutter_config: ^2.0.2
  package_info_plus: ^5.0.1
  flutter_google_places_sdk: ^0.2.2
  flutter_google_maps_webservices: ^1.1.1
  clock: ^1.1.1
  debounce_throttle: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: false
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
